- name: Copy STG pipeline job to temporary directory
  copy:
    src: "../templates/STG-pipeline_job.xml"
    dest: "/tmp/STG-pipeline_job.xml"
  delegate_to: localhost
  run_once: true

- name: Copy PRD pipeline job to temporary directory
  copy:
    src: "../templates/PRD-pipeline_job.xml"
    dest: "/tmp/PRD-pipeline_job.xml"
  delegate_to: localhost
  run_once: true

- name: Copy STG pipeline template to temporary directory
  copy:
    src: "../templates/STG-generic_pipeline.groovy"
    dest: "/tmp/STG-generic_pipeline.groovy"
  delegate_to: localhost
  run_once: true

- name: Copy PRD pipeline template to temporary directory
  copy:
    src: "../templates/PRD-generic_pipeline.groovy"
    dest: "/tmp/PRD-generic_pipeline.groovy"

- name: Create STG Pipeline job
  jenkins_job:
    name: STG-App
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "http://localhost:8080"
    config: "{{ lookup('file', '/tmp/STG-pipeline_job.xml') }}"



- name: Create PRD Pipeline job
  jenkins_job:
    name: PRD-App
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "http://localhost:8080"
    config: "{{ lookup('file', '/tmp/PRD-pipeline_job.xml') }}"