- name: Install Jenkins Job DSL plugin
  jenkins_plugin:
    name: job-dsl
    state: present
  tags: plugins


- name: Copy STG pipeline template to temporary directory
  copy:
    src: "../templates/STG-generic_pipeline.groovy"
    dest: "/tmp/STG-generic_pipeline.groovy"
  delegate_to: localhost
  run_once: true

- name: Copy PRD pipeline template to temporary directory
  copy:
    src: "../templates/PRD-generic_pipeline.groovy"
    dest: "/tmp/PRD-generic_pipeline.groovy"

- name: Create STG Pipeline job
  jenkins_job:
    name: STG-App
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "http://localhost:8080"
    config: |
      pipelineJob('STG-App') {
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                              url('https://github.com/your/repo.git')
                          }
                          branches('*/master') // Or the branch you want to build from
                      }
                  }
              }
              scriptPath('/tmp/STG-generic_pipeline.groovy') // Path to your Jenkinsfile in the repository
          }
      }
  tags: create_jenkins_job

- name: Create PRD Pipeline job
  jenkins_job:
    name: PRD-App
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "http://localhost:8080"
    config: |
      pipelineJob('PRD-App') {
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                              url('https://github.com/your/repo.git')
                          }
                          branches('*/master') // Or the branch you want to build from
                      }
                  }
              }
              scriptPath('/tmp/PRD-generic_pipeline.groovy') // Path to your Jenkinsfile in the repository
          }
      }
  tags: create_jenkins_job
