---

- name: Add Credentials to Jenkins
  jenkins_script:
    script: "{{ lookup('file', '../templates/add_credentials.groovy') }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"

