---

- name: Upload configuration scripts
  template:
    src: "../configuration_as_code/{{ item }}.j2"
    dest: "{{ jenkins_home }}/casc_configs/{{ item }}"
    owner: "{{ jenkins_os_user }}"
    group: "{{ jenkins_os_group }}"
    mode: 0640
  loop:
    - credentials.yml
    - jenkins.yml
  notify: Restart Jenkins