- name: Copy pipeline template to temporary directory
  copy:
    src: "../templates/STG-generic_pipeline.groovy"
    dest: "/tmp/STG-generic_pipeline.groovy"
  delegate_to: localhost
  run_once: true

- name: Copy pipeline template to temporary directory
  copy:
    src: "../templates/STG-generic_pipeline.groovy"
    dest: "/tmp/STG-generic_pipeline.groovy"

- name: Read STG pipeline script from file
  slurp:
    src: "/tmp/STG-generic_pipeline.groovy"
  register: pipeline_stg_script

- name: Read PRD pipeline script from file
  slurp:
    src: "/tmp/PRD-generic_pipeline.groovy"
  register: pipeline_prd_script

- name: Create STG Jenkins job
  jenkins_script:
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "http://localhost:8080"
    script: |
      def pipelineScript = new String('{{ pipeline_stg_script.content | b64decode | replace("\n", "\\n") }}', 'UTF-8')
      hudson.model.Job job = Jenkins.instance.createProject(hudson.model.FreeStyleProject, 'PRD-App')
      job.updateNextBuildNumber(1)
      job.definition = new org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition(pipelineScript, true)
    sandbox: false  


- name: Create PRD Jenkins job
  jenkins_script:
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "http://localhost:8080"
    script: |
      def pipelineScript = new String('{{ pipeline_prd_script.content | b64decode | replace("\n", "\\n") }}', 'UTF-8')
      hudson.model.Job job = Jenkins.instance.createProject(hudson.model.FreeStyleProject, 'PRD-App')
      job.updateNextBuildNumber(1)
      job.definition = new org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition(pipelineScript, true)
    sandbox: false  