---

- name: Render Groovy Template
  template:
    src: ../templates/variables.groovy.j2
    dest: /tmp/variables.groovy

- name: Read Generated Script
  slurp:
    src: /tmp/variables.groovy
  register: script_content

- name: Execute Groovy Script
  uri:
    url: http://localhost:8080/scriptText
    method: POST
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    body: "{{ script_content.content | b64decode }}"
    body_format: raw
    status_code: 200