- name: Copy STG pipeline job to temporary directory
  copy:
    src: "../templates/STG-generic_pipeline.groovy"
    dest: "/tmp/STG-generic_pipeline.groovy"
  delegate_to: localhost
  run_once: true

- name: Read pipeline.groovy content
  slurp:
    src: "/tmp/STG-generic_pipeline.groovy"
  register: groovy_content

- debug:
    var: groovy_content.content
- debug:
    var: groovy_content

- name: Convert Groovy to XML
  set_fact:
    job_xml: |
      <flow-definition plugin="workflow-job@2.40">
        <actions/>
        <description>STG-Pipeline-Job</description>
        <keepDependencies>false</keepDependencies>
        <properties/>
        <definition class="org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition" plugin="workflow-cps@2.90">
            <scriptText>
                {{ groovy_content.content | b64decode | indent(14) }}
            </scriptText>
            <sandbox>false</sandbox>
        </definition>
        <triggers/>
      </flow-definition>


- name: Write job config XML
  copy:
    content: "{{ job_xml }}"
    dest: /tmp/STG-pipeline_job.xml

- name: Download Jenkins CLI JAR
  get_url:
    url: "{{ jenkins_cli_url }}"
    dest: "{{ jenkins_home }}"
    mode: '0755'  # Make the downloaded file executable

- name: Create Jenkins job using CLI
  command: >
    {{ jenkins_cli_command }}
    -s http://localhost:8080/
    -auth {{ jenkins_admin_username }}:{{ jenkins_admin_username }}
    create-job STG-Pipeline-Job
  args:
    stdin: "{{ lookup('file', '/tmp/STG-pipeline_job.xml') }}"

