---

- name: Render Groovy Template
  template:
    src: ../templates/variables.groovy.j2
    dest: /tmp/variables.groovy

- name: Read Generated Script
  slurp:
    src: /tmp/variables.groovy
  register: script_content

- name: Get Jenkins Crumb
  uri:
    url: http://localhost:8080/crumbIssuer/api/json
    method: GET
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
  register: crumb_response

- set_fact:
    jenkins_crumb: "{{ crumb_response.json.crumb }}"

- name: Execute Groovy Script
  uri:
    url: http://localhost:8080/scriptText
    method: POST
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    body: "{{ script_content.content | b64decode }}"
    body_format: raw
    headers:
      Jenkins-Crumb: "{{ jenkins_crumb }}"
    status_code: 200