- name: Copy STG pipeline job to temporary directory
  copy:
    src: "../templates/STG-pipeline_job.xml"
    dest: "/tmp/STG-pipeline_job.xml"
  delegate_to: localhost
  run_once: true

- name: Download Jenkins CLI JAR
  get_url:
    url: "{{ jenkins_cli_url }}"
    dest: "{{ jenkins_home }}"
    mode: '0755'  # Make the downloaded file executable

- name: Configure Jenkins Job
  command: "{{ jenkins_cli_command }} -s http://localhost:8080/ -auth {{ jenkins_admin_username }}:{{ jenkins_admin_username }} create-job {{ job_name }} < /tmp/STG-pipeline_job.xml"
  delegate_to: localhost
