---

- name: Render Groovy Template
  template:
    src: ../templates/variables.groovy.j2
    dest: /tmp/variables.groovy

- name: Read Generated Script
  slurp:
    src: /tmp/variables.groovy
  register: script_content

- name: Install Jenkins Global Environment Variables
  jenkins_script:
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "http://localhost:8080"
    script: "{{ lookup('file', '/tmp/variables.groovy') }}"
