- name: Copy STG pipeline job to temporary directory
  copy:
    src: "../templates/STG-generic_pipeline.groovy"
    dest: "/tmp/STG-generic_pipeline.groovy"
  delegate_to: localhost
  run_once: true

- name: Read STG-generic_pipeline.groovy content
  slurp:
    src: "/tmp/STG-generic_pipeline.groovy"
  register: groovy_content

- name: Convert STG Groovy to XML
  set_fact:
    job_xml: |
      <?xml version='1.1' encoding='UTF-8'?>
        <flow-definition plugin="workflow-job@1342.v046651d5b_dfe">
          <description></description>
          <keepDependencies>false</keepDependencies>
          <properties/>
          <definition class="org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition" plugin="workflow-cps@3774.v4a_d648d409ce">
            <script>
                {{ groovy_content.content | b64decode | indent(14) }}
            </script>
            <sandbox>true</sandbox>
          </definition>
        <triggers/>
        <disabled>false</disabled>
      </flow-definition>


- name: Write STG job config XML
  copy:
    content: "{{ job_xml }}"
    dest: /tmp/STG-pipeline_job.xml

- name: Download Jenkins CLI JAR
  get_url:
    url: "{{ jenkins_cli_url }}"
    dest: "{{ jenkins_home }}"
    mode: '0755'  # Make the downloaded file executable

- name: Create Jenkins STG job using CLI
  command: >
    {{ jenkins_cli_command }}
    -s http://localhost:8080/
    -auth {{ jenkins_admin_username }}:{{ jenkins_admin_username }}
    create-job STG-App
  args:
    stdin: "{{ lookup('file', '/tmp/STG-pipeline_job.xml') }}"



- name: Copy PRD pipeline job to temporary directory
  copy:
    src: "../templates/PRD-generic_pipeline.groovy"
    dest: "/tmp/PRD-generic_pipeline.groovy"
  delegate_to: localhost
  run_once: true


- name: Read PRD-generic_pipeline.groovy content
  slurp:
    src: "/tmp/PRD-generic_pipeline.groovy"
  register: groovy_content

- name: Convert PRD Groovy to XML
  set_fact:
    job_xml: |
        <?xml version='1.1' encoding='UTF-8'?>
        <flow-definition plugin="workflow-job@1342.v046651d5b_dfe">
          <description></description>
          <keepDependencies>false</keepDependencies>
          <properties/>
          <definition class="org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition" plugin="workflow-cps@3774.v4a_d648d409ce">
            <script>
            <script>
                {{ groovy_content.content | b64decode | indent(14) }}
            </script>
            <sandbox>true</sandbox>
          </definition>
        <triggers/>
        <disabled>false</disabled>
      </flow-definition>



- name: Write PRD job config XML
  copy:
    content: "{{ job_xml }}"
    dest: /tmp/PRD-pipeline_job.xml

- name: Create Jenkins PRD job using CLI
  command: >
    {{ jenkins_cli_command }}
    -s http://localhost:8080/
    -auth {{ jenkins_admin_username }}:{{ jenkins_admin_username }}
    create-job PRD-App
  args:
    stdin: "{{ lookup('file', '/tmp/PRD-pipeline_job.xml') }}"

