---

- name: Add Username/Password credentials
  jenkins_script:
    script: |
      import com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl;
      import hudson.util.Secret;

      def domain = com.cloudbees.plugins.credentials.domains.Domain.global()

      {% for cred in credentials %}
      def cred{{ loop.index }} = new UsernamePasswordCredentialsImpl(
        com.cloudbees.plugins.credentials.CredentialsScope.GLOBAL,
        "{{ cred.id }}",
        "{{ cred.id }}",
        "Username/Password credentials",
        "{{ cred.username }}",
        "{{ cred.password }}"
      );
      domain.addCredentials(
        com.cloudbees.plugins.credentials.CredentialsScope.GLOBAL,
        cred{{ loop.index }}
      );
      {% endfor %}
    jenkins_url: "http://localhost:8080"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
