---
# tasks file for  install the jenkins
- name: Create systemd override directory if not exists
  file:
    path: /usr/lib/systemd/system/jenkins.service.d
    state: directory
    mode: '0755'

- name: Copy modified jenkins.repo to override directory
  copy:
    src: ../templates/jenkins.repo
    dest: /usr/lib/systemd/system/jenkins.service.d/jenkins.repo
    mode: '0644'

- name: Download jenkins.repo
  get_url:
    url: "{{ jenkins_Repo }}"
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins Key
  rpm_key:
    state: present
    key: "{{ jenkins_key }}"

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Create custom init scripts directory
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: "{{ jenkins_os_user }}"
    group: "{{ jenkins_os_group }}"
    mode: 0775

- name: Set default user
  template:
    src: "../templates/basic-security.groovy.j2"
    dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    owner: "{{ jenkins_os_user }}"
    group: "{{ jenkins_os_group }}"
    mode: 0755
    
- name: Create configuration as code directory
  file:
    path: "{{ jenkins_home }}/casc_configs"
    state: directory
    owner: "{{ jenkins_os_user }}"
    group: "{{ jenkins_os_group }}"
    mode: 0775

- name: Start & Enable Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: true
      
- name: 
  shell:
      sudo usermod -a -G docker jenkins
      
- name: Get init password Jenkins
  shell: "cat {{ jenkins_home }}/secrets/initialAdminPassword"
  changed_when: false
  register: result
 
- name: Print init password Jenkins
  debug:
    var: result.stdout
    
- name: Change file ownership, group and permissions to docker.sock
  ansible.builtin.file:
    path: /var/run/docker.sock
    owner: root
    group: docker
    mode: '0777'
    
- name: Validate the sudoers file before saving
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
    create: yes
     
- name: Create .m2/repository
  shell: "sudo mkdir -p {{ jenkins_home }}/.m2/repository/"
     
- name: Change permissions .m2/repository
  shell: "sudo chmod -R 777 {{ jenkins_home }}/.m2/repository/"
     
- name: Create directory .shh
  shell: "sudo mkdir -p  {{ jenkins_home }}/.ssh/"

- name: Create file known_hosts
  shell: "sudo touch {{ jenkins_home }}/.ssh/known_hosts"

- name: Change permissions known_hosts
  shell: "sudo chmod -R 777 {{ jenkins_home }}/.ssh/known_hosts"






