---
- name: Install required package for debconf-show
  package:
    name: debconf-utils
    state: present

- name: Set root password for MariaDB
  community.mysql.mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    login_user: root
    login_password: ""
    check_implicit_admin: true

- name: Install MariaDB server
  package:
    name: mariadb-server
    state: present

- name: Start MariaDB service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Copy SQL script to remote host
  copy:
    src: sonarqube_setup.sql
    dest: /tmp/sonarqube_setup.sql  # Destination path on the remote host
    mode: '0644'

- name: Execute SQL script in MariaDB
  mysql_db:
    name: sonarqube_db
    state: import
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    target: /tmp/sonarqube_setup.sql  