---
- name: Install Python3 and pip
  shell: "sudo yum install python3 && sudo yum install python3-pip -y && sudo yum install gcc -y && sudo yum install python3-devel -y"

- name: Install psycopg2 using pip for Python 3
  pip:
    name: psycopg2-binary
    state: present
    executable: pip3

- name: Install PostgreSQL using yum
  shell: "sudo yum install postgresql-server -y"
  args:
    warn: false  

- name: Create PostgreSQL data directory
  file:
    path: /var/lib/pgsql/data
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Initialize PostgreSQL database
  command: postgresql-setup initdb
  become_user: postgres

- name: Start PostgreSQL service
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create SonarQube database and user
  become_user: postgres
  postgresql_user:
    name: "{{ sonarqube_db_user }}"
    password: "{{ sonarqube_db_password }}"
    login_user: postgres
    login_host: localhost

- name: Create SonarQube database
  become_user: postgres
  postgresql_db:
    name: "{{ sonarqube_db_name }}"
    owner: "{{ sonarqube_db_user }}"
    login_user: postgres
    login_host: localhost