- name: Install Python3 and pip
  shell: "sudo yum install python3 && sudo yum install python3-pip -y && sudo yum install gcc -y && sudo yum install python3-devel -y"

- name: Install psycopg2 using pip for Python 3
  pip:
    name: psycopg2-binary
    state: present
    executable: pip3

- name: Install PostgreSQL using yum
  yum:
    name: postgresql-server
    state: latest

- name: Create PostgreSQL data directory
  file:
    path: /var/lib/pgsql/data
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Change permissions data directory
  shell: sudo chmod -R 700 /var/lib/pgsql/data

- name: Initialize PostgreSQL database
  command: postgresql-setup initdb
  become_user: postgres

- name: Update PostgreSQL authentication method in pg_hba.conf
  blockinfile:
    path: /var/lib/pgsql/data/pg_hba.conf
    block: |
      # Allow password-based authentication for all connections
      local   all             all                                     md5
    marker: "# {mark} ANSIBLE MANAGED BLOCK"

- name: Start PostgreSQL service
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create SonarQube database and user
  become_user: postgres
  postgresql_user:
    name: "{{ sonarqube_db_user }}"
    password: "{{ sonarqube_db_password }}"
    login_user: postgres
    login_host: localhost
