---
- name: Install PostgreSQL
  shell: "sudo yum install postgresql-server -y"

- name: Start and enable PostgreSQL service
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create SonarQube database and user
  become_user: postgres
  postgresql_user:
    name: "{{ sonarqube_db_user }}"
    password: "{{ sonarqube_db_password }}"
    login_user: postgres
    login_host: localhost

- name: Create SonarQube database
  become_user: postgres
  postgresql_db:
    name: "{{ sonarqube_db_name }}"
    owner: "{{ sonarqube_db_user }}"
    login_user: postgres
    login_host: localhost
