---
# tasks file for tomcat_setup_check

- name: Install docker compose plugin
  shell: "sudo yum install docker-compose-plugin"
    
- name: Start & Enable docker
  systemd:
      name: docker
      state: started
      enabled: true