# tasks/main.yml
---
- name: Add SonarQube Repository
  yum_repository:
    name: sonarqube
    baseurl: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-8.9.1.44547.zip
    description: SonarQube Repository
    enabled: yes
    gpgcheck: no

- name: Install SonarQube
  yum:
    name: sonarqube
    state: latest

- name: Start SonarQube service
  service:
    name: sonarqube
    state: started
    enabled: yes