# tasks/main.yml
---
- name: Run docker-compose command
  command: docker-compose up -d
  args:
    chdir: sonarqube/templates
  become: yes
  become_user: root

- name: Check if Sonar API is available
  wait_for:
    port: 9000
    delay: 10

