---
# tasks file for tomcat_setup_check

- name: install the latest version of Docker
  yum:
    name: docker
    state: latest
    
- name: Start & Enable docker
  systemd:
      name: docker
      state: started
      enabled: true