---
# tasks file for Apache Maven

- name: check if apache-maven exists or not
  stat:
    path: /opt/{{ maven_package }}
  register: apache_maven_installed

- name: "maven is install" 
  debug:
     msg: "{{ maven_package }} is exists"
  when: apache_maven_installed.stat.exists == True
  
- name: "maven is not installed"
  debug:
    msg: "{{ maven_package }} doesn't exists"
  when: apache_maven_installed.stat.exists == False

- name: downloading maven packages
  get_url:
    url: "{{ maven_url  }}"
    dest: /opt
    mode: 0755
  when: apache_maven_installed.stat.exists == False

- name: extract packages
  unarchive:
    src: /opt/{{ maven_package }}-bin.tar.gz
    dest: /opt
    remote_src: yes
  when: apache_maven_installed.stat.exists == False

- name: change permissions on apache maven file
  file:
    path: /opt/{{ maven_package }}
    mode: 0755
    recurse: yes
  when: apache_maven_installed.stat.exists == False