---
- name: Playbook to jenkins setup
  hosts: localhost
  become: true
  gather_facts: yes
  

  vars_files:
    - jenkins/vars/main.yml
    - jenkins/vars/plugins.yml
    - jenkins/vars/credentials.yml

  vars_prompt:
    - name: jenkins_admin_username
      prompt: Jenkins temporary admin user
      private: no
    - name: jenkins_admin_password
      prompt: Jenkins temporary admin password
      private: yes

  tasks:

    - name: Install Jenkins
      import_tasks: jenkins/tasks/main.yml

  handlers:
    - import_tasks: jenkins/handlers/main.yml
