---
# tasks file for  install the jenkins

- name: Download jenkins.repo
  get_url:
      url: "{{ jenkins_Repo }}"
      dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins Key
  rpm_key:
      state: present
      key: "{{ jenkins_key }}"

- name: Install Jenkins
  yum:
     name: jenkins
     state: present

- name: Start & Enable Jenkins
  systemd:
      name: jenkins
      state: started
      enabled: true
      
- name: 
  shell:
      sudo usermod -a -G docker jenkins
      
      
- name: Get init password Jenkins
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result
 
- name: Print init password Jenkins
  debug:
    var: result.stdout
- name: Change file ownership, group and permissions to docker.sock
  ansible.builtin.file:
    path: /var/run/docker.sock
    owner: root
    group: docker
    mode: '0777'
    
- name: Validate the sudoers file before saving
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
    create: yes
     
- name: Create .m2/repository
  shell: sudo mkdir -p /var/lib/jenkins/.m2/repository/
     
- name: Change permissions .m2/repository
  shell: sudo chmod -R 777 /var/lib/jenkins/.m2/repository/
     
- name: Create directory known_hosts
  shell: sudo mkdir -p  /var/lib/jenkins/.ssh/known_hosts

- name: Create Jenkins Init User
  community.general.jenkins_script:
    script: |
      import jenkins.model.Jenkins
      import hudson.security.HudsonPrivateSecurityRealm
      import hudson.security.FullControlOnceLoggedInAuthorizationStrategy

      def jenkins = Jenkins.instance

      // Define the username and password for the initial user
      def username = "jenkins"
      def password = "jenkins"

      def securityRealm = new HudsonPrivateSecurityRealm(false)
      securityRealm.createAccount(username, password)
      jenkins.setSecurityRealm(securityRealm)

      def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
      jenkins.setAuthorizationStrategy(strategy)

      jenkins.save()
  when: result.stdout is defined 

- name: Install Jenkins Plugins
  community.general.jenkins_plugin:
    name: "{{ item }}"
    url_username: "jenkins"
    url_password: "jenkins"
    jenkins_url: "http://localhost:8080"  # Adjust URL as per your Jenkins instance
    state: present
  loop:
    - aws-credentials
    - amazon-ec2
    - conditional-buildstep